### ISSUE TITLE
[Furniture Overhaul Library (v 1.0.9)] Crash upon opening modded chest from Medieval Fashion (v2.01.17)

### ISSUE THREAD

**Issue by Schiz0r** [MisterAndyDandy/Vintage-Story-Mods-Issue#2]
Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.18.5 (Stable)
6/26/2023 14:40:22: Critical error occurred in the following mod: furniturelibrary@1.0.9
Loaded Mods: aculinaryartillery@1.0.12, betterruins@0.2.1, cavecontent@1.0.1, FarmSurvival@1.3.0, fastermetal@1.0.0, furniturelibrary@1.0.9, medieval@2.01.17, meteoricexpansion@1.2.4, moreclasses@1.2.5, morenails@1.1.0, NoMoreDrifterThrowing@1.0.0, optimizedleathertwo@2.0.0, optimizedpreservation@1.0.0, OresAPlenty@3.1.0, RangedWeapons@0.6.2, dzsalvageplus@1.0.1, sfaws@1.0.0, tprunes@1.0.8, game@1.18.5, animalcages@2.1.5, cooperativecombat@1.1.0, expandedfoods@1.6.6, fishing@1.1.3, hudclock@3.2.0, sailboat@1.1.0, lavoisier@1.2.8, lessclasspenalties@1.0.0, petai@1.7.9, claywheel@1.1.0, stonebakeoven@1.0.3, th3dungeon@0.1.2, usefulstuff17@1.1.6, creative@1.18.5, vsquest@0.4.1, survival@1.18.5, waypointtogether@1.0.1, xlib@0.7.4, metalrecovery@0.1.19-pre.1, knapster@2.4.2, bullseye@2.5.0-rc.1, chemistrylib@1.1.4, tradercamps@1.0.5, feverstonewilds@1.2.0, vsquestexample@0.3.0, xskills@0.7.4, kosfire@1.1.3, kosphotography@1.2.2
System.NullReferenceException: Object reference not set to an instance of an object.
   at furniture.BlockEntityContainers.OnInvOpened(IPlayer player) in C:\Users\andy-\Documents\GitHub\Furniture-Library\mods-src\furniture\src\BlockEntity\BlockEntityContainer.cs:line 248
   at Vintagestory.API.Common.OnInventoryOpenedDelegate.Invoke(IPlayer player)
   at Vintagestory.API.Common.InventoryBase.Open(IPlayer player) in VintagestoryApi\Common\Inventory\InventoryBase.cs:line 819
   at Vintagestory.API.Client.GuiDialogBlockEntity.OnGuiOpened() in VintagestoryApi\Client\UI\Dialog\GuiDialogBlockEntity.cs:line 153
   at Vintagestory.API.Client.GuiDialogBlockEntityInventory.OnGuiOpened() in VintagestoryApi\Client\UI\Dialog\GuiDialogBlockEntityInventory.cs:line 116
   at Vintagestory.API.Client.GuiDialog.TryOpen() in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 283
   at Vintagestory.GameContent.BlockEntityOpenableContainer.OnReceivedServerPacket(Int32 packetid, Byte[] data) in VSSurvivalMod\BlockEntity\BEOpenableContainer.cs:line 137
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandleBlockEntityMessage(Packet_Server packet) in VintagestoryLib\Client\Systems\GeneralPacketHandler.cs:line 438
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 746
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 163
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 681
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 625
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 119
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 476
   at OpenTK.GameWindow.DispatchRenderFrame() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 452
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 375
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
`==================================`
{ TimeGenerated = 6/23/2023 09:23:51, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.18.5.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 2d74

Start Time: 01d9a5d435911817

Termination Time: 3

Application Path: E:\Games\Vintagestory\Vintagestory.exe

Report Id: 983af830-30d1-4be6-a8f6-bfa8067d51f9

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }
`--------------`
{ TimeGenerated = 6/23/2023 09:11:22, Site = , Source = Application Hang, Message = The program Vintagestory.exe version 1.18.5.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.

Process ID: 1d5c

Start Time: 01d9a5d34872d853

Termination Time: 4

Application Path: E:\Games\Vintagestory\Vintagestory.exe

Report Id: 7f4ecb62-28de-434a-97be-30fbbe4aa054

Faulting package full name: 

Faulting package-relative application ID: 

Hang type: Unknown
 }

**Comment by MisterAndyDandy** [comment]
Sorry for late reply back I have been off coding for a bit because it take some much time to fix issue or to make new things. I'll be coming back to this tomorrow so hopefully I can fix it thanks for reporting.
