### ISSUE TITLE
[Furniture Overhaul Library (v 1.0.9)] Crash in Guidebook and Creative Inventory with Medieval Fashion v2.02.12

### ISSUE THREAD

**Issue by Devaraja99** [MisterAndyDandy/Vintage-Story-Mods-Issue#3]
Running on 64 bit Windows 10.0.19045.0 with 32649 MB RAM
Game Version: v1.19.0 (Stable)
1/17/2024 2:19:19 PM: Critical error occurred in the following mod: furniturelibrary@1.0.9
Loaded Mods: furniturelibrary@1.0.9, medieval@2.02.12, game@1.19.0, creative@1.19.0, survival@1.19.0
System.MissingFieldException: Field not found: 'Vintagestory.API.Client.ItemRenderInfo.ModelRef'.
   at furniture.BlockContainers.OnBeforeRender(ICoreClientAPI capi, ItemStack itemstack, EnumItemRenderTarget target, ItemRenderInfo& renderinfo)
   at Vintagestory.Client.NoObf.InventoryItemRenderer.GetItemStackRenderInfo(ClientMain game, ItemSlot inSlot, EnumItemRenderTarget target, Single dt) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 315
   at Vintagestory.Client.NoObf.InventoryItemRenderer.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Single dt, Boolean shading, Boolean origRotate, Boolean showStackSize) in VintagestoryLib\Client\Render\InventoryItemRenderer.cs:line 194
   at Vintagestory.Client.NoObf.RenderAPIGame.RenderItemstackToGui(ItemSlot inSlot, Double posX, Double posY, Double posZ, Single size, Int32 color, Boolean shading, Boolean rotate, Boolean showStacksize) in VintagestoryLib\Client\API\RenderAPIGame.cs:line 274
   at Vintagestory.GameContent.GuiHandbookItemStackPage.RenderListEntryTo(ICoreClientAPI capi, Single dt, Double x, Double y, Double cellWidth, Double cellHeight) in VSSurvivalMod\Systems\Handbook\Gui\GuiHandbookItemStackPage.cs:line 102
   at Vintagestory.GameContent.GuiElementFlatList.RenderInteractiveElements(Single deltaTime) in VSSurvivalMod\Systems\Handbook\Gui\GuiElementFlatList.cs:line 194
   at Vintagestory.API.Client.GuiComposer.Render(Single deltaTime) in VintagestoryApi\Client\UI\GuiComposer.cs:line 716
   at Vintagestory.API.Client.GuiDialog.OnRenderGUI(Single deltaTime) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 384
   at Vintagestory.GameContent.GuiDialogHandbook.OnRenderGUI(Single deltaTime) in VSSurvivalMod\Systems\Handbook\Gui\GuiDialogHandbook.cs:line 493
   at Vintagestory.Client.NoObf.GuiManager.OnRenderFrameGUI(Single deltaTime) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 318
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1006
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 318
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries for Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 1/16/2024 11:21:21 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x4b78
Faulting application start time: 0x01da49147510b6b6
Faulting application path: D:\Games\Vintagestory\Vintagestory.exe
Faulting module path: D:\Games\Vintagestory\Lib\openal32.dll
Report Id: a0f5ac46-9ea1-417f-803e-769085391d48
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 12/24/2023 2:12:47 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x2438
Faulting application start time: 0x01da36b37365e2c0
Faulting application path: D:\Games\Vintagestory\Vintagestory.exe
Faulting module path: D:\Games\Vintagestory\Lib\openal32.dll
Report Id: e9ce8de1-92ff-4d2e-8511-e5e39ddbf1e2
Faulting package full name: 
Faulting package-relative application ID:  }
--------------
{ TimeGenerated = 12/22/2023 10:14:50 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.19.0.0, time stamp: 0x65310000
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0xd38
Faulting application start time: 0x01da35646c1b7a22
Faulting application path: D:\Games\Vintagestory\Vintagestory.exe
Faulting module path: D:\Games\Vintagestory\Lib\openal32.dll
Report Id: 43c12945-00d4-421c-aeef-09476574880c
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by Devaraja99** [comment]
Issue resolved in v1.0.11. Cheers! :)

**Comment by MisterAndyDandy** [comment]
I am glad
